title: "Victor"
description: "A computational model of the English language."
baseurl: /victor
permalink: /:title
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
sass:
  style: compressed
